language: cpp

stages:
  - artifacts
jobs:
  include:
    - stage: artifacts
      name: "linux"
      os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - sudo apt-get update -y && sudo apt-get install -y ccache cmake python-pip
        - pip install --user awscli
        - aws --version
      install:
        - sudo util/build_prep/bootstrap_boost.sh -m
      script:
        - mkdir build; pushd build; cmake .. -DBOOST_ROOT=/usr/local/boost -DNANO_POW_STANDALONE=TRUE -DCMAKE_CXX_COMPILER_LAUNCHER=ccache; cmake --build . --target package --config Release -- -j2; popd
        - if [[ $TRAVIS_PULL_REQUEST == false ]]; then ci/travis-deploy.sh; fi
    - name: "osx"
      os: osx
      compiler: clang
      before_install:
        - brew update;
        - brew cask install xquartz;
        - brew upgrade cmake;
      install:
        - pip install --user awscli
        - brew install ccache;
        - export PATH="$HOME/Library/Python/2.7/bin:/usr/local/opt/ccache/libexec:$PATH";
        - aws --version
      script:
        - mkdir build; pushd build; cmake .. -DNANO_POW_STANDALONE=TRUE -DCMAKE_CXX_COMPILER_LAUNCHER=ccache; cmake --build . --target package --config Release -- -j2; popd
        - if [[ $TRAVIS_PULL_REQUEST == false ]]; then ci/travis-deploy.sh; fi
    - name: "windows"
      os: windows
      cache:
        - ccache: false
      before_install:
        - choco install -y boost-msvc-14.1
        - choco install -y awscli
      script:
        - mkdir build; pushd build; cmake .. -DNANO_POW_STANDALONE=TRUE -G"Visual Studio 15 2017" -A"x64"; cmake --build . --target package --config Release -- -m:2; popd
        - if [[ $TRAVIS_PULL_REQUEST == false ]]; then ci/travis-deploy.sh; fi
cache:
  - ccache: true
  - directories:
    - $HOME/.local
    - $HOME/Library/Caches/Homebrew
